require_relative "schema/atomic_application_update_schema"
require_relative "schema/application_instance_schema"
require_relative "schema/application_instance_configuration_schema"
require_relative "schema/application_instance_general_settings_schema"
require_relative "schema/application_instance_xml_config_schema"
require_relative "schema/application_instance_trial_details_schema"
require_relative "schema/application_instance_license_details_schema"

module AtomicAdmin
  module Schema
  end
end
